setono_sylius_age_verification_shop_initiate:
    path: /age-verification/initiate
    methods: [GET]
    defaults:
        _controller: Setono\SyliusAgeVerificationPlugin\Controller\InitiateVerificationAction

setono_sylius_age_verification_shop_callback:
    path: /age-verification/callback
    methods: [GET]
    defaults:
        _controller: Setono\SyliusAgeVerificationPlugin\Controller\VerifyIdCallbackAction
